### ISSUE TITLE
Cannot set NSHighResolutionCapable to "true" in info.plist

### ISSUE THREAD

**Issue by lanthale** [gluonhq/client-maven-plugin#10]
I have compiled a sample javafx application with maven and notice that on my mac all is unsharp. After manually change the info.plist and adding "NSHighResolutionCapable:true" the issue is fixed.

How can I add this to the compile chain permanently ?

**Comment by jperedadnr** [comment]
Thanks for reporting.

I've included your suggestion in the default plist file that will be created if the user's project doesn't contain one.

You can test this change already, if you use the `0.0.2-SNAPSHOT` version of the client-maven-plugin.

Make sure you add also this repository:
```
<pluginRepository>
            <id>gluon-snapshots</id>
            <url>http://nexus.gluonhq.com/nexus/content/repositories/public-snapshots/</url>
        </pluginRepository>
```
and remove the `src/mac` folder (so a new one will be created) from your project.

Let us know if that works for you.

**Comment by lanthale** [comment]
It is working now. 
Thank you for the fast fix.

Clemens
