### ISSUE TITLE
Support for Kotlin app (TornadoFX)

### ISSUE THREAD

**Issue by tlvenn** [gluonhq/client-maven-plugin#116]
Hi, would it be possible to use this maven plugin with a Kotlin app ? Right now it seems I cant really provide properly the main entry point class.

Maybe it works oob already but I just don't know the correct syntax to use to reference my Kotlin main class ?

Thanks in advance.

**Comment by jperedadnr** [comment]
You can use Kotlin. I've managed to combine the Kotlin plugin with the Client plugin, combining Java and Kotlin classes. 
We need an entry point, and we have to add (at least for now) `public static void main(String... args) { launch(args); }` to the main class.

**Comment by tlvenn** [comment]
Hi @jperedadnr,

Ya I just figured that out from the TornadoFX doc:

![image](https://user-images.githubusercontent.com/3340262/72984172-cb647e80-3e2e-11ea-812f-b7e19e2399a5.png)

Thanks for your feedback !

**Comment by tlvenn** [comment]
I can properly compile now however the linking emit a little error but ends up linking nonetheless:

![image](https://user-images.githubusercontent.com/3340262/72984459-78d79200-3e2f-11ea-9190-8969dbeb03de.png)

However, when I try to start the native app, it does not work:

![image](https://user-images.githubusercontent.com/3340262/72984504-9278d980-3e2f-11ea-8fbf-9fac7ca89f8b.png)

With this main class:

![image](https://user-images.githubusercontent.com/3340262/72984577-c522d200-3e2f-11ea-9f39-6f03d08ec73c.png)
 
Any idea what could be the issue ?

**Comment by jperedadnr** [comment]
Note in general that you need to use the `reflectionList`, and include all the classes that are used by reflection (and that are not already included in target/client/$arch/gvm/reflectionconfig-$arch.json)

In this case, com.example.demo.app.MyApp might be added to that json file, however there is no public constructor? That would explain the missing <init>() method?

As a possible workaround, can you create a Java launcher class?

**Comment by tlvenn** [comment]
Hi @jperedadnr,

Adding 'com.example.demo.app.MyApp' to the reflectionList helps going further.
I was then able to compile and link properly.

When i run the native app, i got the following error:
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/3340262/73053911-bfcb9300-3ed4-11ea-9fea-8c2c01880c01.png">

So I added the view to the reflectionList as well but now the link step is failing:

![image](https://user-images.githubusercontent.com/3340262/73053966-f4d7e580-3ed4-11ea-82cd-b8657a326ba9.png)

Any idea what could be the culprit this time ? Thanks again for your help.

**Comment by jperedadnr** [comment]
That issue should be solved running with a newer GraalVM version. Latest is 19.3.1 https://github.com/graalvm/graalvm-ce-builds/releases

**Comment by tlvenn** [comment]
Yeah it works now 🎉 

As soon as the window get the focus, an error is emitted but I am guessing this has nothing to do with Kotlin but probably a bug with Gluon substrate:

![image](https://user-images.githubusercontent.com/3340262/73143427-65ede780-40e5-11ea-80d4-e10cc3f754ff.png)

**Comment by jperedadnr** [comment]
No, no bug, just same issue as discussed before: everything that is accessed reflectively has to be added to a reflection config file. Substrate does this for a majority of JavaFX core classes and methods (see [config files](https://github.com/gluonhq/substrate/tree/master/src/main/resources/config), but it doesn't cover _all_ of them.

For that you can add missing classes and/or methods in your particular case to a json file, as documented: https://docs.gluonhq.com/client/#_config_files

Feel free to close this issue.

**Comment by tlvenn** [comment]
But how do you decide if it should be part of Substrate config files or left to the end user ? It seems to me that in that particular case it should be the former as I would expect it would happen on pretty much all javafx apps running on OSX.

**Comment by jperedadnr** [comment]
Fair question: adding all the possible JavaFX core classes and methods that can be used via reflection at some point (for instance when using FXML), has some impact in compilation time and memory footprint.
Ideally we should have an automatic tool that will detect which classes are going to be required, but so far we have to do it manually. Substrate provides one set of classes/methods, and the rest has to be added in the project. Anyway we keep adding more classes regularly.

**Comment by tlvenn** [comment]
Thanks a lot for the guidance to sort this out @jperedadnr
