### ISSUE TITLE
Command line args

### ISSUE THREAD

**Issue by NO-ob** [gluonhq/client-maven-plugin#120]
When launching with command lines arguments length is 0 do I need to add a link in pom to get them to work?

**Comment by xzel23** [comment]
I think this is something that should really be covered in the samples, i.e. when launching helloFX with an optional name passed as a command line parameter. In the current form, the samples pass `args` on to `Application.launch()`, which suggests that everything should work as expected, but `args` is really always just an empty array, no matter what you give on the command line.

Sorry, I can only support you in stressing how important this is, but I have not found the answer myself.

**Comment by metacodez** [comment]
I stumbled over the empty `args` array as well. Is there any workaround on getting hold of the actually passed arguments?

**Comment by jperedadnr** [comment]
Fixed with #566
