### ISSUE TITLE
libdarwin.a not found 

### ISSUE THREAD

**Issue by rladstaetter** [gluonhq/client-maven-plugin#150]
trying out your client-samples, namely HelloFX project, with macos catalina 10.15.3.

following your instructions, when executing

```
mvn clean client:build
```

it takes a while, finally it bails out with
```
[Fri Mar 20 22:41:15 CET 2020][FINE] PB Command for link: gcc /Users/lad/temp/client-samples/Maven/HelloFX/target/client/x86_64-darwin/gvm/hellofx/AppDelegate.o /Users/lad/temp/client-samples/Maven/HelloFX/target/client/x86_64-darwin/gvm/hellofx/launcher.o /Users/lad/temp/client-samples/Maven/HelloFX/target/client/x86_64-darwin/gvm/tmp/SVM-1584740358209/hellofx.hellofx.o /Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/libjava.a /Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/libnio.a /Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/libzip.a /Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/libnet.a /Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/libprefs.a /Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/libj2pkcs11.a /Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/libsunec.a /Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/libextnet.a /Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/svm/clibraries/darwin-amd64/libffi.a /Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/svm/clibraries/darwin-amd64/libjvm.a /Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/svm/clibraries/darwin-amd64/libstrictmath.a /Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/svm/clibraries/darwin-amd64/libdarwin.a -lpthread -lz -ldl -lstdc++ -lobjc -Wl,-framework,Foundation -Wl,-framework,AppKit -Wl,-framework,ApplicationServices -Wl,-framework,OpenGL -Wl,-framework,QuartzCore -Wl,-framework,Security -Wl,-force_load,/Users/lad/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/darwin-x86_64/sdk/lib/libglass.a -Wl,-force_load,/Users/lad/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/darwin-x86_64/sdk/lib/libjavafx_font.a -Wl,-force_load,/Users/lad/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/darwin-x86_64/sdk/lib/libjavafx_iio.a -Wl,-force_load,/Users/lad/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/darwin-x86_64/sdk/lib/libprism_es2.a -o /Users/lad/temp/client-samples/Maven/HelloFX/target/client/x86_64-darwin/hellofx -L/Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/svm/clibraries/darwin-amd64 -L/Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib -L/Users/lad/.gluon/substrate/javafxStaticSdk/15-ea+gvm16/darwin-x86_64/sdk/lib
[Fri Mar 20 22:41:15 CET 2020][FINE] Start process link...
[Fri Mar 20 22:41:15 CET 2020][INFO] [SUB] clang: error: no such file or directory: '/Users/lad/bin/graalvm-ce-java11-20.0.0/Contents/Home/lib/svm/clibraries/darwin-amd64/libdarwin.a'
[Fri Mar 20 22:41:15 CET 2020][FINE] Result for link: 1
[Fri Mar 20 22:41:15 CET 2020][SEVERE] Process link failed with result: 1
```

i'm using graalvm 20.0.0

any ideas?

**Comment by jperedadnr** [comment]
Can you try this GraalVM version instead?
https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-darwin-20.1.0-ea+26.zip

**Comment by rladstaetter** [comment]
i've downloaded this version of graalvm.

$GRAALVM_HOME/lib/svm/clibraries/darwin-amd64/libdarwin.a exists in this version.

set GRAALVM_HOME, JAVA_HOME to the base directory of this unpacked zip, after that also the PATH to $GRAALVM_HOME/bin

I've executed mvn client:build but it won't start, since MacOs Catalina informs me that 'java' is not trusted- as such I've executed

```
sudo xattr -r -d com.apple.quarantine /path/to/graalvm-svm-darwin-20.1.0-ea+26/
```

(digged that out somewhere in graal issue tracker)

I've executed `mvn client:build`, afterwards `mvn client.run` like described at https://github.com/gluonhq/client-samples.

A javafx window appears and greets me with a success message. Great! 👍

Some remarks:

during build, logs say:

```
Mar 21, 2020 3:33:02 PM com.gluonhq.substrate.util.Logger logSevere
SEVERE: Process check attr failed with result: 1
Check the log files under null
And please check https://docs.gluonhq.com/client/ for more information.
Mar 21, 2020 3:33:02 PM com.gluonhq.substrate.util.Logger logInfo
INFO: Logging process [check attr] to file: /Users/lad/temp/client-samples/Maven/HelloGluon/target/client/log/process-check attr-1584801182296.log
```

log file contains:

```
Process
=======
check attr

Command Line
============
xattr -p com.apple.quarantine /path/to/graalvm-svm-darwin-20.1.0-ea+26

Output
======
xattr: /path/to/graalvm-svm-darwin-20.1.0-ea+26: No such xattr: com.apple.quarantine


Result
======
result: 1    
```

Moreover, it struck me that i hadn't performed `gu install native-image`, but it worked anyway?  it is a little confusing that i had to set  GRAALVM_HOME directly to the base directory, not to <unzipped dir>/Contents/Home like in the docs described for MacOs with graalvm 20.0.0 (which doesnt work for me)

when trying to executing `gu install native-image`I get an error message 'Error: The GraalVM directory <dir where graalvm was unpacked>/bin is invalid.'

anyhow, in HelloFX/target/client/x86_64-darwin/ I find a binary with about 62 MB which apparently contains everything the application needs to start and run! great! 

HelloWorld, HelloFX, HelloFxml, HelloGluon can be compiled and successfully executed.

finally, another unrelated question ... is at about 60 MB the minimum size one has to expect for javafx apps or is it possible to reduce the footprint even further? (HelloWorld has about 30 MB)

**Comment by gargoyle** [comment]
I had the same issue as reported here, and rladstaetters final comments also worked for me to get the `mvn client:link` stage working. 

However, the `mvn client:package` does not work. It reports success, but fails checking for `xattr` values that had to be removed to allow the programs to run.

Any ideas when this version of graalvm might make it to a final release? (Properly signed and ready to run on OSX)

**Comment by mipastgt** [comment]
@gargoyle The `build:package` documentation says: _At the moment, this goal is only supported for iOS and Android_. So, if you are building for macOS then this is currently non-functional.

**Comment by gargoyle** [comment]
Ahh. I missed that bit - thanks.
