### ISSUE TITLE
undefined reference to 'JVM_LatestUserDefinedLoader'

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/client-maven-plugin#172]
I am trying to compile a first basic version of my software for Android but after 41 minutes of building it fails with the following error message: undefined reference to 'JVM_LatestUserDefinedLoader'
(See attached log file for more detailed output.) I have no idea where that comes from and after searching on Google it seems I am not the only one with this problem. It is also strange that this exact same code builds just fine on my Mac. I can also build the HelloFX from the client samples with my setup for Android without problems.

This attempt of an Android build was done on:
Windows 10 running WSL2 with Ubuntu 20.04
Gluon Client plugin for Maven 0.1.23
https://download2.gluonhq.com/substrate/graalvm/graalvm-svm-linux-20.1.0-ea+28.zip

[client-debug0.log.1.zip](https://github.com/gluonhq/client-maven-plugin/files/4580228/client-debug0.log.1.zip)

**Comment by jperedadnr** [comment]
Is this still an issue with the latest versions? Else, can we close it?

**Comment by mipastgt** [comment]
This seems very old (from May). I think that can be closed.
