### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/client-maven-plugin#185]
In the just released new version of the README.md you say under Linux and Android
... by choosing `graalvm-ce-java11-darwin-amd64-20.2.0-dev.tar.gz`. I doubt this is correct. This should probably be `graalvm-ce-java11-linux-amd64-20.2.0-dev.tar.gz`.

**Comment by jperedadnr** [comment]
Thx, good catch, fixed.
