### ISSUE TITLE
Error: Invalid or corrupt jarfile C:\Users\Rus\.m2\repository\net\sf\jagg\jagg\0.9.0\jagg-0.9.0.pom

### ISSUE THREAD

**Issue by zrb80** [gluonhq/client-maven-plugin#186]
An error occurs during the build of the project. mvn clean client:build

![image](https://user-images.githubusercontent.com/31654430/83337885-c1b0c300-a2c7-11ea-916f-56ef2709f2d5.png)

[pom.xml.zip](https://github.com/gluonhq/client-maven-plugin/files/4706323/pom.xml.zip)

I tried before this to collect examples. [https://github.com/gluonhq/client-samples/tree/master/Maven](url)
Everything turns out well. Examples work.

**Comment by zrb80** [comment]
Can anyone help me resolve the issue. How to deal with type dependencies
        `<dependency>
            <groupId> net.sf.jagg </groupId>
            <artifactId> jagg </artifactId>
            <version> 0.9.0 </version>
            <type>**pom**</type>
        </dependency>`
An error occurs during assembly, specified in the above screenshot.
What to do in such cases?

**Comment by jperedadnr** [comment]
The issue is that every dependency found in the project is added to the classpath that native-image uses to compile and generate the native image, without any filter. While probably that should be taken care of from the plugin directly, you can probably remove it from the pom and add `net.sf.jaggjagg-core` instead?

**Comment by jperedadnr** [comment]
You can test Client plugin 0.1.32-SNAPSHOT, that should fix your issue (keeping the pom dependency). Add:
```
<pluginRepositories>
    <pluginRepository>
        <id>snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    </pluginRepository>
</pluginRepositories>
```
