### ISSUE TITLE
iOS Assets - AppIconSet

### ISSUE THREAD

**Issue by cbm64chris** [gluonhq/client-maven-plugin#188]
Hey, I am trying to apply a set of iPhone icons to a build. I have an ios directory beneath src and I have created png files that match the resolution in Xcode 11 for iPhone with a Contents.json as below.

Is there something that I am still missing?

```
{
  "images" : [
	{
      "size" : "120x120",
      "idiom": "iphone",
	  "filename" : "weightconverter-iphone-app-icon-120@2x.png",
      "scale": "2x"
    },
    {
      "size" : "180x180",
      "idiom": "iphone",
      "filename" : "weightconverter-iphone-app-icon-180@3x.png",
      "scale": "3x"
    },
    {
      "size" : "40x40",
      "idiom": "iphone",
      "filename" : "weightconverter-iphone-notification-icon-40@2x.png",
      "scale": "2x"
    },
    {
      "size" : "60x60",
      "idiom": "iphone",
      "filename" : "weightconverter-iphone-notification-icon-60@3x.png",
      "scale": "3x"
    },
    {
      "size" : "58x58",
      "idiom": "iphone",
      "filename" : "weightconverter-iphone-spotlight-settings-icon-58@2x.png",
      "scale": "2x"
    },
    {
      "size" : "87x87",
      "idiom": "iphone",
      "filename" : "weightconverter-iphone-spotlight-settings-icon-87@3x.png",
      "scale": "3x"
    },
    {
      "size" : "80x80",
      "idiom": "iphone",
      "filename" : "weightconverter-iphone-spotlight-icon-80@2x.png",
      "scale": "2x"
    },
    {
      "size" : "120x120",
      "idiom": "iphone",
      "filename" : "weightconverter-iphone-spotlight-icon-120@3x.png",
      "scale": "3x"
    },
    {
      "size" : "1024x1024",
      "idiom" : "ios-marketing",
      "filename" : "weightconverter-app-store-icon-1024@1x.png",
      "scale" : "1x"
    }
  ],
  "info" : {
    "version" : 1,
    "author" : "xcode"
  }
}
```

**Comment by jperedadnr** [comment]
The plugin creates the iOS assets by default under `target/client/ios_arm64/gensrc/ios/, you can move then to `src/ios`, and then replace the required files with yours.

See for reference on the folders you have to create: https://github.com/gluonhq/ChatApp/tree/master/App/src/ios

**Comment by cbm64chris** [comment]
Yeah, I have that and all the icons are there but upon build and deploy to a connected the device the app has no icon. i.e ![default from apple](https://cdn.dribbble.com/users/127815/screenshots/1108928/icon-dribbble.jpg).

**Comment by jperedadnr** [comment]
Does it work with the default Gluon icon, when you don't set the `src/ios` folder?

**Comment by cbm64chris** [comment]
Yes.

**Comment by jperedadnr** [comment]
Then I suggest you copy `target/client/ios_arm64/gensrc/ios` into `src/ios`, and run `client:link client:run` again, that will give you still the Gluon icon.
Once that works, replace the Gluon icon files with yours, file by file, and change the name in the contents.json file. link and run again?

**Comment by cbm64chris** [comment]
Ok, I have it - must have just been a typo in the json somewhere. Thx!
