### ISSUE TITLE
Regression from 0.1.26 to 0.1.27 on OSX

### ISSUE THREAD

**Issue by dropofwill** [gluonhq/client-maven-plugin#190]
Running the JavaFX samples from [the client samples project](https://github.com/gluonhq/client-samples) all fail for me on Graal 20.1 Java 11/XCode 10.1/High Sierra with linker errors about StrictMath:

```
[Tue Jun 09 09:56:56 EDT 2020][INFO] [SUB]   "_StrictMath_asin", referenced from:
[Tue Jun 09 09:56:56 EDT 2020][INFO] [SUB]       ___svm_version_info in com.gluonhq.hello.hellogluon.o
[Tue Jun 09 09:56:56 EDT 2020][INFO] [SUB]   "_StrictMath_atan2", referenced from:
[Tue Jun 09 09:56:56 EDT 2020][INFO] [SUB]       ___svm_version_info in com.gluonhq.hello.hellogluon.o
[Tue Jun 09 09:56:56 EDT 2020][INFO] [SUB]   "_StrictMath_cbrt", referenced from:
[Tue Jun 09 09:56:56 EDT 2020][INFO] [SUB]       ___svm_vm_target_staticlibraries in com.gluonhq.hello.hellogluon.o
[Tue Jun 09 09:56:56 EDT 2020][INFO] [SUB]   "_StrictMath_hypot", referenced from:
[Tue Jun 09 09:56:56 EDT 2020][INFO] [SUB]       ___svm_cglobaldata_base in com.gluonhq.hello.hellogluon.o
[Tue Jun 09 09:56:56 EDT 2020][INFO] [SUB] ld: symbol(s) not found for architecture x86_64
[Tue Jun 09 09:56:56 EDT 2020][INFO] [SUB] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[Tue Jun 09 09:56:56 EDT 2020][SEVERE] Process link failed with result: 1
```

Downgrading to 0.1.27 fixed this and generated working sample projects.

Note the Hello World sample worked in either case, it was just the JavaFX projects that failed.

**Comment by mipastgt** [comment]
When you use 0.1.27 you also have to upgrade your GraalVM installation. Have a look at the 
[README](https://github.com/gluonhq/client-maven-plugin/blob/master/README.md#mac-os-x-and-ios) For macOS it currently is `graalvm-ce-java11-darwin-amd64-20.2.0-dev.tar.gz`

**Comment by jperedadnr** [comment]
Upgrade the GraalVM version from https://github.com/graalvm/graalvm-ce-dev-builds/releases, there was a recent change in GraalVM, and that requires a more recent version.

**Comment by dropofwill** [comment]
Gotcha, missed the -dev bit just downloaded the latest from the releases. Thanks!
