### ISSUE TITLE
[0.1.27] - fatal error LNK1120: 5 unresolved externals

### ISSUE THREAD

**Issue by QQ34205037** [gluonhq/client-maven-plugin#192]
An error occurred when I used the 0.1.27 plug-in to generate the native executable file. There is no such error when I used the 0.1.26 plug-in.
Can someone tell me how to fix it, thank you.

Log:

Process
=======
link

Command Line
============
link D:\projects\idea\client-samples\Maven\HelloFX\target\client\x86_64-windows\gvm\hellofx\launcher.obj D:\projects\idea\client-samples\Maven\HelloFX\target\client\x86_64-windows\gvm\tmp\SVM-1591945158709\hellofx.hellofx.obj advapi32.lib iphlpapi.lib secur32.lib userenv.lib ws2_32.lib j2pkcs11.lib java.lib net.lib nio.lib prefs.lib fdlibm.lib sunec.lib zip.lib ffi.lib jvm.lib libchelper.lib /NODEFAULTLIB:libcmt.lib /SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup comdlg32.lib dwmapi.lib gdi32.lib imm32.lib shell32.lib uiautomationcore.lib urlmon.lib winmm.lib glass.lib javafx_font.lib javafx_iio.lib prism_common.lib prism_d3d.lib /WHOLEARCHIVE:glass.lib /WHOLEARCHIVE:javafx_font.lib /WHOLEARCHIVE:javafx_iio.lib /WHOLEARCHIVE:prism_common.lib /WHOLEARCHIVE:prism_d3d.lib /OUT:D:\projects\idea\client-samples\Maven\HelloFX\target\client\x86_64-windows\hellofx.exe /LIBPATH:D:\applications\graalvm-ce-java11-20.2.0-dev\lib\svm\clibraries\windows-amd64 /LIBPATH:D:\applications\graalvm-ce-java11-20.2.0-dev\lib /LIBPATH:C:\Users\HAMLET\.gluon\substrate\javafxStaticSdk\15-ea+gvm20\windows-x86_64\sdk\lib

Output
======
Microsoft (R) Incremental Linker Version 14.26.28806.0
Copyright (C) Microsoft Corporation.  All rights reserved.

   Creating library D:\projects\idea\client-samples\Maven\HelloFX\target\client\x86_64-windows\hellofx.lib and object D:\projects\idea\client-samples\Maven\HelloFX\target\client\x86_64-windows\hellofx.exp
hellofx.hellofx.obj : error LNK2001: unresolved external symbol StrictMath_acos
hellofx.hellofx.obj : error LNK2001: unresolved external symbol StrictMath_asin
hellofx.hellofx.obj : error LNK2001: unresolved external symbol StrictMath_atan2
hellofx.hellofx.obj : error LNK2001: unresolved external symbol StrictMath_cbrt
hellofx.hellofx.obj : error LNK2001: unresolved external symbol StrictMath_hypot
D:\projects\idea\client-samples\Maven\HelloFX\target\client\x86_64-windows\hellofx.exe : fatal error LNK1120: 5 unresolved externals

Result
======
result: 1120

**Comment by jperedadnr** [comment]
Please upgrade to a recent GraalVM build from here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

**Comment by QQ34205037** [comment]
@jperedadnr This error has been resolved after upgrading. Thank you very much.
