### ISSUE TITLE
Wrong GRAALVM_HOME for macOS/iOS

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/client-maven-plugin#193]
On the README.md page of this project you ask people to make the following export
`export GRAALVM_HOME=/opt/graalvm-ce-java11-20.2.0-dev`
in the macOS/iOS section. Is this correct? It only works for me if I add the usual `/Contents/Home` to it, which is the standard for Java VMs on the Mac. If I remember it correctly it was only your special version, which you provided before we could use the official releases, which did not follow this convention.

**Comment by jperedadnr** [comment]
Thanks for reporting. Fixed.
