### ISSUE TITLE
Windows not yet supported as target option

### ISSUE THREAD

**Issue by kristofdho** [gluonhq/client-maven-plugin#198]
setting `<target>windows</target>` is not yet supported.
It should be included here:

https://github.com/gluonhq/client-maven-plugin/blob/59ff1c5e9daf9ae51e73dcb97eb888740d856cf1/src/main/java/com/gluonhq/NativeBaseMojo.java#L146-L165

**Comment by jperedadnr** [comment]
If you are building a native image in your host machine, you would set `<target>host</target>`, which is the default. This applies for Linux, Mac and Windows, where host and target are the same machine.

Only if you are building for Android or Embedded (from a Linux machine), or iOS (on a Mac), you would set a different target. 

There is no supported cross compilation to build for Windows from Linux or Mac.
