### ISSUE TITLE
Linking fails due to missing libraries

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/client-maven-plugin#203]
After some time I tried again to build on Mac but the link step failed due to missing libraries in the GraalVM.
```
[Di. Juni 30 14:42:55 MESZ 2020][FINE] Start process link...
[Di. Juni 30 14:42:55 MESZ 2020][INFO] [SUB] clang: error: no such file or directory: '/Users/mpaus/tools/graalvm-ce-java11-20.2.0-dev/Contents/Home/lib/libjava.a'
[Di. Juni 30 14:42:55 MESZ 2020][INFO] [SUB] clang: error: no such file or directory: '/Users/mpaus/tools/graalvm-ce-java11-20.2.0-dev/Contents/Home/lib/libnio.a'
[Di. Juni 30 14:42:55 MESZ 2020][INFO] [SUB] clang: error: no such file or directory: '/Users/mpaus/tools/graalvm-ce-java11-20.2.0-dev/Contents/Home/lib/libzip.a'
[Di. Juni 30 14:42:55 MESZ 2020][INFO] [SUB] clang: error: no such file or directory: '/Users/mpaus/tools/graalvm-ce-java11-20.2.0-dev/Contents/Home/lib/libnet.a'
[Di. Juni 30 14:42:55 MESZ 2020][INFO] [SUB] clang: error: no such file or directory: '/Users/mpaus/tools/graalvm-ce-java11-20.2.0-dev/Contents/Home/lib/libprefs.a'
[Di. Juni 30 14:42:55 MESZ 2020][INFO] [SUB] clang: error: no such file or directory: '/Users/mpaus/tools/graalvm-ce-java11-20.2.0-dev/Contents/Home/lib/libj2pkcs11.a'
[Di. Juni 30 14:42:55 MESZ 2020][INFO] [SUB] clang: error: no such file or directory: '/Users/mpaus/tools/graalvm-ce-java11-20.2.0-dev/Contents/Home/lib/libfdlibm.a'
[Di. Juni 30 14:42:55 MESZ 2020][INFO] [SUB] clang: error: no such file or directory: '/Users/mpaus/tools/graalvm-ce-java11-20.2.0-dev/Contents/Home/lib/libsunec.a'
[Di. Juni 30 14:42:55 MESZ 2020][INFO] [SUB] clang: error: no such file or directory: '/Users/mpaus/tools/graalvm-ce-java11-20.2.0-dev/Contents/Home/lib/libextnet.a'
```
This is due to the fact that these libraries have been moved to a different location.
They are now located in `...graalvm-ce-java11-20.2.0-dev/Contents/Home/lib/static/darwin-amd64`

**Comment by tiainen** [comment]
Resolved with https://github.com/gluonhq/substrate/pull/680

**Comment by mipastgt** [comment]
Am I supposed to build that myself because the current client-maven-plugin does not pull that in automatically? Or are you planning an update shortly?

**Comment by tiainen** [comment]
You can use a snapshot build: `com.gluonhq:client-maven-plugin:0.1.28-SNAPSHOT` which has a dependency to the latest snapshot build of `com.gluonhq:substrate:0.0.26-SNAPSHOT`.

Make sure to add the sonatype snapshot repository to your pom.xml:

    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases><enabled>false</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>
    </repositories>

**Comment by mipastgt** [comment]
That's good to know. Thank you.
Michael
