### ISSUE TITLE
OutOfMemoryError - Could not allocate an aligned heap chunk

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/client-maven-plugin#215]
After all the most recent changes I can now build and install my app on Android again.
(Client 0.1.29-SNAPSHOT and latest GraalVM 20.3.0-dev from July 25th).
However it only seems to work on my Galaxy Tab S4 (Android 10) but
not on my Samsung Galaxy S7 phone (Android 8). When launched via mvn client:run the app
immediately crashes on the phone with `Fatal error: unhandled exception in isolate 0x150150150150150: java.lang.OutOfMemoryError: Could not allocate an aligned heap chunk` I even rebooted the device (just in case)
but it did not make any difference. The same app was previously working perfectly on that phone.

Here is the full log
[outofmemory_crash_log.zip](https://github.com/gluonhq/client-maven-plugin/files/4975715/outofmemory_crash_log.zip)

**Comment by mipastgt** [comment]
Just verified that even the small HelloGluon sample app crashes with exactly the same message. So it cannot really be an issue of not having enough memory. This app worked nicely on my phone before the recent changes.

Message attached:
[hellogluon_outofmemory_crash_log.zip](https://github.com/gluonhq/client-maven-plugin/files/4975851/hellogluon_outofmemory_crash_log.zip)

**Comment by jperedadnr** [comment]
@mipastgt We are investigating a possible issue after https://github.com/gluonhq/substrate/pull/697. 

Before we merge a possible fix, It would be great if you could clone https://github.com/jperedadnr/substrate/tree/708-cap in your Linux machine and build Substrate:

`./gradlew clean publishToMavenLocal`

and then build your Android project again, trying to run it on your Android 8 device.

**Comment by mipastgt** [comment]
Will do that on sunday morning.

**Comment by mipastgt** [comment]
Hi, I can confirm that with https://github.com/jperedadnr/substrate/tree/708-cap the same apk-file of my application now works again on both devices (tablet and phone). Thanks a lot for the quick fix.

Do you also have a solution for https://github.com/gluonhq/client-maven-plugin/issues/216 .

**Comment by jperedadnr** [comment]
Fixed with https://github.com/gluonhq/substrate/pull/709
