### ISSUE TITLE
ECKeyPairGenerator_isCurveSupported

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/client-maven-plugin#216]
After all the most recent changes I can now build and install my app on Android again.
(Client 0.1.29-SNAPSHOT and latest GraalVM 20.3.0-dev from July 25th).
However, when I run it on my Galaxy Tab S4 (Android 10) and try to make a https request
I get the following error: `UnsatisfiedLinkError: sun.security.ec.ECKeyPairGenerator.isCurveSupported`.
I tried to add the class to the reflection list but this did not make any difference. This code worked
perfectly before I could not build for Android anymore because of the recent bugs

Here is the full output:
[ECKeyPairGenerator_exception_log.zip](https://github.com/gluonhq/client-maven-plugin/files/4975728/ECKeyPairGenerator_exception_log.zip)
.

**Comment by jperedadnr** [comment]
Have you tried the JNI list?

**Comment by mipastgt** [comment]
Yes.
```
<jniList>
   <list>sun.security.ec.ECKeyPairGenerator</list>
</jniList>
```
To me it looks like the class is there but the method got stripped.

I know this crypto stuff is in a separate module (jdk.crypto.ec) but I don't know how to pull that into native-image properly.

**Comment by mipastgt** [comment]
I also tried to add a native image arg like this as suggested by the comment in the message

`<nativeImageArg>-Djava.library.path=${env.GRAALVM_HOME}/lib/</nativeImageArg>`

but it did not help.

So I created an issue for graalvm/native-image directly.

<https://github.com/oracle/graal/issues/2713>

**Comment by mipastgt** [comment]
I'd like to add that none of the native-image args 
```
--enable-all-security-services
--enable-https
--enable-url-protocols https

```
makes this work. It worked until recently without problems but is now broken.

**Comment by jperedadnr** [comment]
Can you provide a code snippet to reproduce the issue? Just the HelloFX main class modified with an `HttpURLConnection` and an URL that causes the issue?

**Comment by mipastgt** [comment]
Yes, I can do that.

**Comment by mipastgt** [comment]
Here is the requested sample project. It also contains a log file of the build and run error.
[HelloFX.zip](https://github.com/gluonhq/client-maven-plugin/files/5015472/HelloFX.zip)

**Comment by jperedadnr** [comment]
Thanks, I'll try to reproduce it.

**Comment by jperedadnr** [comment]
I can reproduce it.
Might be related to this P2 issue: https://bugs.openjdk.java.net/browse/JDK-8233954

**Comment by mipastgt** [comment]
Hmm, I have seen that too but it is about explicitly removing the sunec library, which is not what I want to do. This issue was also fixed already a long time ago and my code worked until recently. So I assume this issue here is due to some bug introduced after the fix of this P2 issue. The latest dev snapshot of the GraalVM also still contains this lib, so why doesn't it work?

**Comment by mipastgt** [comment]
I just got this from the GraalVM team: https://github.com/oracle/graal/issues/2713#issuecomment-668126836

**Comment by mipastgt** [comment]
There was an update to this issue here: https://github.com/oracle/graal/issues/2713#issuecomment-668669201

**Comment by jperedadnr** [comment]
@mipastgt A workaround has been added to Substrate, while this is properly fixed in GraalVM.

Would you mind testing 0.1.30-SNAPSHOT again?

**Comment by mipastgt** [comment]
I built the latest version of substrate and installed it and used version 0.1.30-SNAPSHOT of the client-maven-plugin. I applied this to the test example as well as my real project and they both seem to work now. Many thanks for the collaborative effort to fix this bug :-)

Do you already know when all the other open pull request for recent bugs will be approved and integrated into the master branch? I'd like to create a consolidated build of all these fixes together in order to get a stable and functional build environment again.

**Comment by jperedadnr** [comment]
Client plugin release 0.1.30 should fix this.
