### ISSUE TITLE
Strange back-button behavior

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/client-maven-plugin#218]
My Android application uses Gluon Charm and a NavigationDrawer to handle the various views. What puzzles me is the strange and inconsistent behavior of the back-button. On my Samsung Galaxy Tab S4 with Android 10 the behavior is to immediately jump back to the users Android home screen whenever I hit the back-button. However the same apk-file installed on my Samsung Galaxy S7 phone with Android 8 shows a different behavior. The NavigationDrawer walks back the stack as expected but once it reaches the applications home screen it refuses to go back to the users Android home screen. I even added a Quit-button which calls the LifecycleService.shutdown method but that does not seem to have any effect either. So my situation is that on the tablet I always get back to the Android home screen, even if that is not intended and on the phone I never get back to that screen even if I want to. If there are any hidden Android switches, which might influence this behavior, please let me know. This has nothing to do with the recent changes because I observe this behavior already for a long time.

**Comment by jperedadnr** [comment]
Using Gluon Mobile, the Back button is used to deal with the view navigation: you can go back from the current view to the previous one, as the user view navigation history is stored in some stack. 

By default, the home view is not part of the stack (so once in it, the back button just quits the app), see SKIP_VIEW_STACK for instance in the Notes app: https://github.com/gluonhq/gluon-samples/blob/substrate/notes/src/main/java/com/gluonhq/samples/notes/views/AppViewManager.java#L50.

In any case, the back button is mapped to the ESC key, so there is this event handler:

```
scene.addEventHandler(KeyEvent.KEY_RELEASED, e -> {
                if (KeyCode.ESCAPE.equals(e.getCode())) {
                    // switchToPreviousView
                }
});
``` 

Can you add it too to your project and print out if its get called when you press Back?

Also check your view stack policy.

**Comment by mipastgt** [comment]
In order to keep things simple for the moment, I did not explicitly specify any ViewStackPolicy. So, the defaults should be used. This leaves me with the questions:

- Why is the behavior different between tablet and phone? Are there any debug settings on device which might cause this?
- Why does the app not go back to the Android home screen once back in the apps home screen and the back button is pressed again? I added the event handler and it is indeed called every time on the phone but never on the tablet.
- Why does explicitly calling the LifecycleService.shutdown method have no effect? Calling Platform.exit instead just leads to a black screen but not to a termination of the app.

**Comment by jperedadnr** [comment]
Hmm, that rings a bell... We fixed this [issue](https://bitbucket.org/javafxports/8u-dev-rt/issues/16/change-of-behaviour-in-android-28-views) a while ago in JavaFXPorts. It might explain why behavior is different between Android 8 and 10.

- As is now with Substrate, on Android 10, the JavaFX view is not focused by default, and pressing back will call the `onDestroy` method from the [MainActivity](https://github.com/gluonhq/substrate/blob/master/src/main/resources/native/android/android_project/app/src/main/java/com/gluonhq/helloandroid/MainActivity.java#L273), so that explains why the app quits immediately. The ESC handler doesn't work, if the scene is not focused.

- On Android 8, on the contrary, the view gets focused, and `onDestroy` is never called. Back button works between views (because of the ESC handler) but doesn't quit the app, because Attach doesn't actually [call](https://github.com/gluonhq/attach/blob/381f6cf02b8b6d41bc282637d37e6c32f722a39d/modules/lifecycle/src/main/java/com/gluonhq/attach/lifecycle/impl/AndroidLifecycleService.java#L39) it.

I'll file issues in Substrate and Attach.

**Comment by jperedadnr** [comment]
Two PRs have been created. 
If you want to give them a try, build Substrate from https://github.com/jperedadnr/substrate/tree/713-focus and Attach from https://github.com/jperedadnr/attach-2/tree/176-shutdown.

**Comment by mipastgt** [comment]
I've built the libs but how do I convince the client-maven-plugin to use the created substrate-0.0.28-SNAPSHOT.

**Comment by jperedadnr** [comment]
Use 0.1.30-SNAPSHOT, and either use the repo:
```
<pluginRepositories>
        <pluginRepository>
            <id>snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </pluginRepository>
    </pluginRepositories>
```
or clone the Client maven plugin and build it (`mvn clean install`).

**Comment by mipastgt** [comment]
I tried this already but the build of 0.1.30-SNAPSHOT seems to be broken.

**Comment by jperedadnr** [comment]
Better build it and install it locally then

**Comment by mipastgt** [comment]
Ok, did that. The result is:
1. Tablet and phone behave identically now.
2. I can walk back the stack with the back-button now as you would expect it.
3. Once I have reached the applications home screen, one further back-button click makes the application hang or even crash.
4. I also cannot terminate the application via the lifecycle shutdown method. The application hangs.
Good night
Michael

**Comment by jperedadnr** [comment]
Great, thanks for testing. and notifying the shutdown crash issue. It should be solved now with this: https://github.com/jperedadnr/attach-2/commit/673a618a7c67a2fa6bd598dc03351ef5a052dc27

**Comment by mipastgt** [comment]
I just tried your last patch. The result is:
1. Tablet and phone behave identically now.
2. I can walk back the stack with the back-button now as you would expect it.
3. Once I have reached the applications home screen, one further back-button click terminates the application as it should.
4. Explicitly calling the lifecycle shutdown method also terminates the application as it should.

When terminating, the application seems to go through the states `pause`, `stop`, `destroy` but a lifecycle event listener like this

`LifecycleService.create().ifPresent(ls -> ls.addListener(LifecycleEvent.PAUSE, () -> log.info("Application paused.")));
`

is never called.

One further question remains: What should I do to prevent termination of the application via the last back-button click?

Michael

**Comment by jperedadnr** [comment]
About Pause not called, once the activity finishes, pause, stop and destroy states are forwarded via `notifyLifecycleEvent` and Attach "sees" those events. The app should see them too. Your listener works for me (just replaced `log.info` with `System.out.println`):

```
[mar. jul. 28 11:05:36 CEST 2020][INFO] [SUB] V/GluonAttach(  544): DalvikLifecycleService::shutdown
[mar. jul. 28 11:05:36 CEST 2020][INFO] [SUB] V/GraalActivity(  544): onPause
[mar. jul. 28 11:05:36 CEST 2020][INFO] [SUB] D/GluonAttach(  544): Call Attach method from native Lifecycle: pause
[mar. jul. 28 11:05:36 CEST 2020][INFO] [SUB] D/GraalCompiled(  544): Application paused.
[mar. jul. 28 11:05:37 CEST 2020][INFO] [SUB] V/GraalActivity(  544): onStop
[mar. jul. 28 11:05:37 CEST 2020][INFO] [SUB] D/GluonAttach(  544): Call Attach method from native Lifecycle: stop
[mar. jul. 28 11:05:37 CEST 2020][INFO] [SUB] V/GraalActivity(  544): onDestroy
[mar. jul. 28 11:05:37 CEST 2020][INFO] [SUB] D/GluonAttach(  544): Call Attach method from native Lifecycle: destroy
...
```

For the back-button, you can simply prevent the handler with an event filter:

```
scene.addEventFilter(KeyEvent.KEY_RELEASED, e -> {
            if (KeyCode.ESCAPE.equals(e.getCode())) {
                e.consume();
            }
        });
```
Make sure you have some condition about doing it only for the home view.

**Comment by mipastgt** [comment]
Filtering the back-button works as you said but call me crazy, this code

```
log.info("Add listener for LifecycleEvent.PAUSE.");
LifecycleService.create().ifPresentOrElse(ls -> ls.addListener(LifecycleEvent.PAUSE,
   () -> System.out.println(">>> Application paused <<<")),
   () -> System.out.println("No LifecycleService available."));
```
gets executed on the postInit method of my MobileApplication class but it does not print anything when I terminate the application via an explicit call to the LifeCycle.shutdown method.

```
[Tue Jul 28 12:04:58 CEST 2020][INFO] [SUB] V/GluonAttach( 1529): DalvikLifecycleService::shutdown
[Tue Jul 28 12:04:58 CEST 2020][INFO] [SUB] V/GraalActivity( 1529): onPause
[Tue Jul 28 12:04:58 CEST 2020][INFO] [SUB] E/GraalGluon( 1529): Dispatching lifecycle event from native Dalvik layer: pause
[Tue Jul 28 12:04:58 CEST 2020][INFO] [SUB] D/GluonAttach( 1529): Call Attach method from native Lifecycle: pause
[Tue Jul 28 12:04:58 CEST 2020][INFO] [SUB] D/GraalGluon( 1529): ATTACH_DALVIK, tid = 1529, existed? 1, dalvikEnv at 0x7dbb0d6200
[Tue Jul 28 12:04:58 CEST 2020][INFO] [SUB] D/GraalGluon( 1529): DETACH_DALVIK, tid = 1572, existed = 0, env at 0x7d789d5200
[Tue Jul 28 12:04:58 CEST 2020][INFO] [SUB] D/GraalGluon( 1529): DETACH_DALVIK, tid = 1529, existed = 1, env at 0x7dbb0d6200
[Tue Jul 28 12:04:58 CEST 2020][INFO] [SUB] D/GluonAttach( 1529): called Attach method from native Lifecycle done
[Tue Jul 28 12:04:59 CEST 2020][INFO] [SUB] V/GraalActivity( 1529): onStop
[Tue Jul 28 12:04:59 CEST 2020][INFO] [SUB] E/GraalGluon( 1529): Dispatching lifecycle event from native Dalvik layer: stop
[Tue Jul 28 12:04:59 CEST 2020][INFO] [SUB] D/GluonAttach( 1529): Call Attach method from native Lifecycle: stop
[Tue Jul 28 12:04:59 CEST 2020][INFO] [SUB] D/GraalGluon( 1529): ATTACH_DALVIK, tid = 1529, existed? 1, dalvikEnv at 0x7dbb0d6200
[Tue Jul 28 12:04:59 CEST 2020][INFO] [SUB] D/GraalGluon( 1529): DETACH_DALVIK, tid = 1529, existed = 1, env at 0x7dbb0d6200
[Tue Jul 28 12:04:59 CEST 2020][INFO] [SUB] D/GluonAttach( 1529): called Attach method from native Lifecycle done
[Tue Jul 28 12:04:59 CEST 2020][INFO] [SUB] V/GraalActivity( 1529): onDestroy
[Tue Jul 28 12:04:59 CEST 2020][INFO] [SUB] E/GraalGluon( 1529): Dispatching lifecycle event from native Dalvik layer: destroy
[Tue Jul 28 12:04:59 CEST 2020][INFO] [SUB] D/GluonAttach( 1529): Call Attach method from native Lifecycle: destroy
[Tue Jul 28 12:04:59 CEST 2020][INFO] [SUB] D/GraalGluon( 1529): ATTACH_DALVIK, tid = 1529, existed? 1, dalvikEnv at 0x7dbb0d6200
[Tue Jul 28 12:04:59 CEST 2020][INFO] [SUB] D/GraalGluon( 1529): DETACH_DALVIK, tid = 1529, existed = 1, env at 0x7dbb0d6200
[Tue Jul 28 12:04:59 CEST 2020][INFO] [SUB] D/GluonAttach( 1529): called Attach method from native Lifecycle done

```

**Comment by jperedadnr** [comment]
Can you try `adb logcat` instead of `mvn client:run`? Sometimes not all the logs are shown with the latter.

Anyway, this is what I have (pretty much the same):

![Captura de pantalla 2020-07-28 a las 12 27 28](https://user-images.githubusercontent.com/2043230/88654656-f4abe300-d0cd-11ea-8a00-a84e35c80961.png)

**Comment by mipastgt** [comment]
I tried `adb logcat` but it doesn't make a difference. Maybe we should postpone further work on this until all the other changes are integrated into the master branches, so that we can be sure to really operate on the same code base.

**Comment by jperedadnr** [comment]
Sure, that makes sense. However, now that you build Attach locally, you could add some debug info and find out...

**Comment by jperedadnr** [comment]
Client plugin release 0.1.30 should fix this. For Attach, 4.0.9-SNAPSHOT.
