### ISSUE TITLE
Set Icon (On windows and MacOS)

### ISSUE THREAD

**Issue by java4tech** [gluonhq/client-maven-plugin#219]
Hi,

Thanks for the work you guys have done. I tried it create native image on windows and MacOS and its very easy to build and use.

Now my question is regarding setting **Icon**!! I have built helloFXML.exe from the example but it comes without ICON. Is there any way to set custom Icon? Tested on Mac and same issue. I'm assuming this is true for all OS (At least Desktop).

**Comment by mipastgt** [comment]
Basically the same answer as in https://github.com/gluonhq/client-maven-plugin/issues/220#issuecomment-670948048 applies here too, at least for macOS. It is relatively easy though to create such an .app bundle with icon yourself. I did it by creating a dummy .app bundle via the jpackage tool, which lets you specify a custom icon and other things and then later opened this .app folder and replaced the launcher with the executable file created by the client-maven-plugin and additionally deleted some other folders which are not needed anymore.

**Comment by java4tech** [comment]
@mipastgt thanks for the tip. I have found the solution for both MacOS and Windows. I'm going to close the issue now.
