### ISSUE TITLE
How to build and deploy to iOS simulator

### ISSUE THREAD

**Issue by samyc1201** [gluonhq/client-maven-plugin#226]
I need to test out something in the simulator, because I can't get console log from device (when I use system.out.println), but follow this guide https://docs.gluonhq.com/client/#_ios, after I execute `mvn client:package`, I got two package, one `app` and another `ipa`.

The `app` should be for simulator but it is built under `arm64-ios` folder, and the simulator log saying (when the app started, it force closed): 

`Program specified by service does not contain any valid architectures for this system.`

The documentation doesn't mention how to change the architectures type for simulator, can anyone advise?

**Comment by mipastgt** [comment]
As far as I know building for the ios simulator is currently not supported.

**Comment by samyc1201** [comment]
yes you are right, confirm with their support team already...
