### ISSUE TITLE
Android Client Build Link Error (libjnidispatch.a:1:1: invalid character)

### ISSUE THREAD

**Issue by LeroyChristopherDunn** [gluonhq/client-maven-plugin#227]
Hi there

My client build with android target fails with a link error:

`[Fri Aug 14 15:56:12 SAST 2020][INFO] ==================== LINK TASK ====================
[Fri Aug 14 15:56:12 SAST 2020][INFO] [SUB] /home/leroy/.gluon/substrate/Android/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.gold: error: /home/leroy/IdeaProjects/androidlinkerror/target/client/aarch64-android/gvm/lib/libjnidispatch.a:1:1: invalid character
[Fri Aug 14 15:56:15 SAST 2020][INFO] [SUB] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[Fri Aug 14 15:56:15 SAST 2020][SEVERE] Process link failed with result: 1`

It fails with the same error specifically when I add our enterprise app as a dependency or include the 'JNA-based (native) Operating System and Hardware Information library for Java' - [OSHI](https://github.com/oshi/oshi), as a dependency

I've included a sample app to replicate the issue which extends the hellofx sample app by simply including the OSHI dependency. If you could please assist with understanding why this issue occurs and how to resolve it, I could update our enterprise app accordingly

I'm using GraalVM CE 20.3.0-dev-20200814_0227 and it's bundled Java on Ubuntu 16.04

[Sample project](https://github.com/LeroyChristopherDunn/graal_android_link_error)
[Pom.xml](https://github.com/LeroyChristopherDunn/graal_android_link_error/blob/master/pom.xml)
[Full error logl](https://github.com/LeroyChristopherDunn/graal_android_link_error/blob/master/client.build.android.error.log)

**Comment by jperedadnr** [comment]
By default, the Client plugin scans all dependencies for static native libraries (*.a), and add them to the project, so these can be linked (see https://github.com/gluonhq/substrate/blob/master/src/main/java/com/gluonhq/substrate/target/AbstractTargetConfiguration.java#L646).

The OSHI jar has a dependency on `net.java.dev.java:jna`, and this jar contains several native libraries, static (*.a) and dynamic (*.so, *.dll, *.jnilib). The static libraries `com/sun/jna/aix-ppc/libjnadispatch.a` or `com/sun/jna/aix-ppc64/libjnadispatch.a` are found and added by the plugin, but later on, `libjnadispatch.a` can't be linked to the project, as its architecture is not correct for Android.

To overcome the issue in your HelloFX sample, this works:
```
<dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>3.13.3</version>
            <exclusions>
                <exclusion>
                    <groupId>net.java.dev.jna</groupId>
                    <artifactId>jna</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

But probably that won't be the case in your project, as there will be some classes from that excluded jar that could be required.

Anyway, even if you could create a jna jar without these *.a files, there are two main issues:

- Do you expect OSHI to work on Android? I see folders for "desktop" only (linux, mac, unix, windows) 
- Do you expect jna to work on Android? I see many dynamic libraries, but not for android 64 bits. Even if there is one, this library should be extracted and added to the jniLibs folder. Similar as explained here https://github.com/gluonhq/substrate/issues/741#issuecomment-673435037.

**Comment by LeroyChristopherDunn** [comment]
Thanks. I didn't expect or require OSHI or JNA to work on Android. Your feedback has helped me identify and remove problematic libraries and now the client build is passing as expected. Thanks for your assistance
