### ISSUE TITLE
Compiling HelloWorld works; Linking fails

### ISSUE THREAD

**Issue by molbertz** [gluonhq/client-maven-plugin#231]
Hi there,

The linking fails with the following errors. Several libraries can't be found.

`Process
=======
link

Command Line
============
gcc /home/me/temp/dev/code/client/hello/target/client/x86_64-linux/gvm/Maven Client CommandLine - Test/launcher.o /home/me/temp/dev/code/client/hello/target/client/x86_64-linux/gvm/tmp/SVM-1597845397408/de.program.o -Wl,-Bstatic -ljava -lnio -lzip -lnet -lprefs -ljvm -lstrictmath -lj2pkcs11 -lsunec -lextnet -llibchelper -Wl,-Bdynamic -lz -ldl -lstdc++ -lpthread -rdynamic -o /home/me/temp/dev/code/client/hello/target/client/x86_64-linux/Maven Client CommandLine - Test -L/opt/graalvm-ce-java11-20.3.0-dev/lib/svm/clibraries/linux-amd64 -L/opt/graalvm-ce-java11-20.3.0-dev/lib

Output
======
/usr/bin/ld: -ljava kann nicht gefunden werden
/usr/bin/ld: -lnio kann nicht gefunden werden
/usr/bin/ld: -lzip kann nicht gefunden werden
/usr/bin/ld: -lnet kann nicht gefunden werden
/usr/bin/ld: -lprefs kann nicht gefunden werden
/usr/bin/ld: -lstrictmath kann nicht gefunden werden
/usr/bin/ld: -lj2pkcs11 kann nicht gefunden werden
/usr/bin/ld: -lsunec kann nicht gefunden werden
/usr/bin/ld: -lextnet kann nicht gefunden werden
collect2: error: ld returned 1 exit status

Result
======
result: 1`

From my understanding the "-L/opt/graalvm-ce-java11-20.3.0-dev/lib" should tell the Linker where to look for those. But something isn't working as all libraries seem to be there.
I've also double checked all pre requisites. Compiler/Linker/Java11/GraalVM. Everything should be there. Any ideas what goes wrong?

**Comment by molbertz** [comment]
Turns out it works once I set the client-maven-plugin version to 0.1.30. It swaps out a library and completes a lookup path. You should update the pages under: https://docs.gluonhq.com/client/#_run_the_samples

You can go ahead and close this issue. Or do I have to do that?

**Comment by jperedadnr** [comment]
Thanks, documentation will be updated today.
