### ISSUE TITLE
possible to build iOS shared library?

### ISSUE THREAD

**Issue by samyc1201** [gluonhq/client-maven-plugin#256]
The [doc](https://docs.gluonhq.com/client/0.1.32/#_clientlink) there mentioned:

```
Links the object file to create a native executable file or shared library.

The results will be available at target/client/$arch-$os/$AppName.
```

I added this in main class:

```
@CEntryPoint(name = "test")
    public static void test(IsolateThread thread) {
    	 System.out.println("Test Hello World!!");
    }
```

Add below in pom.xml:

```
<nativeImageArgs>
	<nativeImageArg>
		--shared
	</nativeImageArg>						
</nativeImageArgs>
```

After that I run `client:build`, there is no  shared library generated in `target/client/$arch-$os/$AppName`, only the iOS executable binary.

I found the generated header file `hello.helloworld.h` contain the method:

```
#ifndef __HELLO_HELLOWORLD_H
#define __HELLO_HELLOWORLD_H

#include <graal_isolate.h>


#if defined(__cplusplus)
extern "C" {
#endif

void test(graal_isolatethread_t*);

int run_main(int paramArgc, char** paramArgv);

void vmLocatorSymbol(graal_isolatethread_t* thread);

#if defined(__cplusplus)
}
#endif
#endif
```
But shared library is not found at the same folder `target/client/arm64-ios/gvm/helloWorld`.

Currently is it possible to do so via gluon maven plugin?

**Comment by samyc1201** [comment]
closed this as I am getting help from Gluon support directly...

**Comment by shafqatevo** [comment]
Can you please share the solution here please?

**Comment by samyc1201** [comment]
@shafqatevo This features doesn't exist in Gluon Client Plugin, it doesn't **directly** (but indirectly) use the native-image to generate the binary, it is based on llvm tech, so it is a bit deep inside, you need to get consult from Gluon support if you want to proceed with the customization.

**Comment by shafqatevo** [comment]
@samyc1201 thanks for the information.

If anyone from Gluon is reading this - how can we help to document the process or add this feature to the plugin? We are exploring this to deploy shared libs in Android and iOS for an open source project.

@johanvos @jperedadnr
