### ISSUE TITLE
KeyCombination not working with client-maven-plugin

### ISSUE THREAD

**Issue by lanthale** [gluonhq/client-maven-plugin#259]
If I am using in my javafx application a keycombination the native image is no longer working and shows the following error message:

Caused by: java.lang.RuntimeException: Cannot create instance of javafx.scene.input.KeyCodeCombination with given set of properties: [code, shortcut, meta, shift, alt, control]

Here is my reflection list:
`
<reflectionList>
                            <list>javafx.fxml.FXMLLoader</list>
                            <list>at.itarchitects.jeditfx.JEditFXController</list>                            
                            <list>de.jensd.fx.glyphs.fontawesome.FontAwesomeIconView</list>                            
                            <list>org.fxmisc.flowless.VirtualizedScrollPane</list>
                            <list>org.fxmisc.richtext.CodeArea</list>
                            <list>org.fxmisc.richtext.LineNumberFactory</list>
                            <list>org.mozilla.universalchardet.UniversalDetector</list>
                            <list>javafx.geometry.Insets</list>
                            <list>javafx.scene.control.Button</list>
                            <list>javafx.scene.control.Label</list>
                            <list>javafx.scene.control.Menu</list>
                            <list>javafx.scene.control.MenuBar</list>
                            <list>javafx.scene.control.MenuItem</list>
                            <list>javafx.scene.control.ProgressBar</list>
                            <list>javafx.scene.control.Tab</list>
                            <list>javafx.scene.control.TabPane</list>                            
                            <list>javafx.scene.input.KeyCharacterCombination</list>
                            <list>javafx.scene.input.KeyCodeCombination</list>
                            <list>javafx.scene.input.KeyCombination</list>                            
                            <list>javafx.scene.input.KeyEvent</list>
                            <list>javafx.scene.input.Mnemonic</list>
                            <list>javafx.geometry.HPos</list>
                            <list>javafx.scene.layout.AnchorPane</list>
                            <list>javafx.scene.layout.ColumnConstraints</list>
                            <list>javafx.scene.layout.GridPane</list>
                            <list>javafx.scene.layout.HBox</list>
                            <list>javafx.scene.layout.RowConstraints</list>
                            <list>javafx.scene.layout.StackPane</list>
                            <list>javafx.scene.layout.VBox</list>
                            <list>javafx.scene.text.Font</list>
                        </reflectionList>
`

**Comment by jperedadnr** [comment]
Post a sample that reproduces the issue (without those many dependencies).

**Comment by jperedadnr** [comment]
Not enough details

**Comment by lanthale** [comment]
Here is the complete project: https://github.com/lanthale/JeditFX
Just clone it and uncomment the gluon plugin section.
Build tool: maven

Hopefully that helps. I do not know why such a big reflection list for such a small program is necessary.
