### ISSUE TITLE
Request: Add ability to pass custom arguments to compiler

### ISSUE THREAD

**Issue by LordTylus** [gluonhq/client-maven-plugin#260]
Hello there,

I am currently evaluating gluon as a possible alternative to RoboVM and now Try to compile our JavaFX Windows App for iOS. However I noticed some issues when compiling. For example I do have a few Classes which contain optional dependencies. Those are currently not Available my Target machine as they are not needed and those methods are never called.

However GraalVM appears to try to compile those not needed Methods anyway and is now very unhappy that it cannot resolve these optional dependencies.

`[Mi. Sep. 23 13:33:26 MESZ 2020][INFO] [SUB] Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.icepdf.core.pobjects.Document. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
[Mi. Sep. 23 13:33:26 MESZ 2020][INFO] [SUB] Trace: 
[Mi. Sep. 23 13:33:26 MESZ 2020][INFO] [SUB] 	at parsing SwingImageUtils.loadFromPDF(SwingImageUtils.java)`

For my evaluation I could easily remove this specific Method as it was not used in this protect anyway but it would be neat I could just pass some custom flags like --allow-incomplete-classpath or --report-unsupported-elements-at-runtime to the GraalVM compiler.

Apparently Gluon/Substrate already has a list of compilerFlags but the Maven Plugin is currently not able to populate it with data. 

If there already is a way to do so with the maven plugin, please let me know.

**Comment by jperedadnr** [comment]
See https://docs.gluonhq.com/client/#_nativeimageargs

**Comment by LordTylus** [comment]
Thank you! This is indeed what I was looking for but I seem to have missed it.
