### ISSUE TITLE
ServiceLoader<DisneyWorldMember> serviceLoader = ServiceLoader.load(DisneyWorldMember.class);

### ISSUE THREAD

**Issue by EvokeAngle** [gluonhq/client-maven-plugin#261]
I posted a demo in [https://github.com/EvokeAngle/client_serviceloader/blob/master/service-consumer/src/main/java/serviceconsumer/Main.java](https://github.com/EvokeAngle/client_serviceloader/blob/master/service-consumer/src/main/java/serviceconsumer/Main.java)

In Intellij idea it run normal : ----Mickey-----Donald-----Goofy-----
but after run :client:client client:run 
there is noting

**Comment by jperedadnr** [comment]
Run the executable in `target/client/x86_64-$os/yourapp` directly from a terminal to find out possible exceptions

**Comment by EvokeAngle** [comment]
[ 9月 24 15:49:09 CST 2020][] PB Command for java-version: D:\software\graalvm-ce-java11-windows-amd64-20.2.0\bin\java --version
[ 9月 24 15:49:09 CST 2020][] Start process java-version...
[ 9月 24 15:49:09 CST 2020][] [SUB] openjdk 11.0.8 2020-07-14
[ 9月 24 15:49:09 CST 2020][] [SUB] OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
[ 9月 24 15:49:09 CST 2020][] [SUB] OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)
[ 9月 24 15:49:09 CST 2020][] Result for java-version: 0
[ 9月 24 15:49:20 CST 2020][] ==================== RUN TASK ====================
[ 9月 24 15:49:20 CST 2020][] PB Command for run until end: D:\workspace\client_serviceloader\service-consumer\target\client\x86_64-windows\service-consumer.exe
[ 9月 24 15:49:20 CST 2020][] Start process run until end...
[ 9月 24 15:49:20 CST 2020][] [SUB] ----
[ 9月 24 15:49:27 CST 2020][] Result for run until end: 0

there is nothing about exception ;
And then i add :
`System.out.println(serviceLoader.findFirst());`

client-debug0.log shows:

[ 9月 24 15:55:34 CST 2020][] ==================== RUN TASK ====================
[ 9月 24 15:55:34 CST 2020][] PB Command for run until end: D:\workspace\client_serviceloader\service-consumer\target\client\x86_64-windows\service-consumer.exe
[ 9月 24 15:55:34 CST 2020][] Start process run until end...
[ 9月 24 15:55:34 CST 2020][] [SUB] Optional.empty
[ 9月 24 15:55:34 CST 2020][] [SUB] ----
[ 9月 24 15:55:36 CST 2020][] Result for run until end: 0

**Comment by jperedadnr** [comment]
Why do you have `AllowIncompleteClasspath`? Better to avoid it, native compilation will fail fast if something is missing.
I don't see a reflection list, but I'd assume that the class called by the service loader should be added.

Can you also test:
```
try {
    ServiceLoader.load(DisneyWorldMember.class);
} catch (Throwable t) { t.printStackTrace(); }
```

**Comment by EvokeAngle** [comment]
I've removed `AllowIncompleteClasspath` , and added  'tyy...catch...' , there is still Still no more output information in client-debug0.log .
And I've found this in ServiceLoader.class : 
`Module callerModule = caller.getModule();`,
Does  current version plugin  supports the Jigsaw?

**Comment by jperedadnr** [comment]
As I mentioned, 
> I don't see a reflection list, but I'd assume that the class called by the service loader should be added.

Have you tried that?

**Comment by EvokeAngle** [comment]
<reflectionList>
    <list>disneyworld.implementation.Donald</list>
    <list>disneyworld.implementation.Goofy</list>
    <list>disneyworld.implementation.Mickey</list>
</reflectionList>

I tried that,but it did't work.

**Comment by jperedadnr** [comment]
That is not what it should be in the `reflectionList`. Your service loader is calling `DisneyWorldMember.class`, therefore you need to add:

`<reflectionList>disneyworld.service.DisneyWorldMember</reflectionList>`
