### ISSUE TITLE
OSX CMD+Q not working

### ISSUE THREAD

**Issue by lanthale** [gluonhq/client-maven-plugin#264]
I have tried now my application with client:build to get a native binary.

The issue is, that normally every application can be terminated under OSX 10.xx (used 10.15.7) with the keyboard shortcut CMD+Q. But the native executable can only be exited via menu which calls "System.exit(0)". 

Here is the project with which I have tried it: https://github.com/lanthale/JeditFX/

**Comment by jperedadnr** [comment]
This issue is related to https://github.com/gluonhq/substrate/issues/118, mainly to this comment: https://github.com/gluonhq/substrate/issues/118#issuecomment-569533473

There is no fix/workaround yet.

**Comment by lanthale** [comment]
Thank you for fast feedback. So I will stay with the Jlink/jpackage build until there is a fix for the issue.
