### ISSUE TITLE
Can't install *.apk on x86 emulators

### ISSUE THREAD

**Issue by molbertz** [gluonhq/client-maven-plugin#265]
Is there a way we can test our apps on an emulator by supplying the needed libs? I keep getting this error:
INSTALL_FAILED_NO_MATCHING_ABIS res=-113

**Comment by jperedadnr** [comment]
Android emulators are not supported yet. You might try https://android-developers.googleblog.com/2020/03/run-arm-apps-on-android-emulator.html

**Comment by molbertz** [comment]
Thanks for the link. The apk installs but when starting I see lots of errors. The most important one seems to be:

10-06 13:26:48.567  6522  6522 D AndroidRuntime: Shutting down VM
10-06 13:26:48.569  6522  6522 E AndroidRuntime: FATAL EXCEPTION: main
10-06 13:26:48.569  6522  6522 E AndroidRuntime: Process: com.bscgmbh.boseclient, PID: 6522
10-06 13:26:48.569  6522  6522 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZdaPv" referenced by "/data/app/~~WxzkuldhQJryUvQXx75BIQ==/com.mycompany.client-w4LXd35t42rxN7XmtUwq7Q==/lib/arm64/libsubstrate.so"...
10-06 13:26:48.569  6522  6522 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
10-06 13:26:48.569  6522  6522 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
10-06 13:26:48.569  6522  6522 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1664)
10-06 13:26:48.569  6522  6522 E AndroidRuntime: 	at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
10-06 13:26:48.569  6522  6522 E AndroidRuntime: 	at android.view.SurfaceView.updateSurface(SurfaceView.java:1153)
10-06 13:26:48.569  6522  6522 E AndroidRuntime: 	at android.view.SurfaceView.lambda$new$0$SurfaceView(SurfaceView.java:173)
