### ISSUE TITLE
Not adjusting window on mobile

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/client-maven-plugin#274]
In my application I have a few TextFields which I would like to edit. Unfortunately some of them are hidden when the virtual keyboard pops up on Android and so I don't see what I am doing. I added
`System.setProperty("com.sun.javafx.vk.adjustwindow", "true");`
to my main method but this does not seem to have any effect. I then also tried to add
`System.setProperty("com.sun.javafx.virtualKeyboard", "javafx");`
but this just resulted in a heavy flickering of the screen.
So, how is it possible to push up the screen, so that the edited fields remain visible above the virtual keyboard?
I tried this on my Samsung Galaxy S7 with client-maven-plugin 0.1.34-SNAPSHOT

**Comment by jperedadnr** [comment]
Did you try the Keyboard service?
https://github.com/gluonhq/attach/tree/master/modules/keyboard

**Comment by mipastgt** [comment]
No, not yet. I thought that is handled automatically when the adjustwindow property is set. If I have to apply that to every text input control in my app manually, then this defeats the idea of WORA, doesn't it?

**Comment by jperedadnr** [comment]
`com.sun.javafx.vk.adjustwindow` is for the `VirtualKeyboard` control that is used in embedded and touch enabled desktop screens. On mobile we use the built-in keyboard, so those are not related. I haven't tried enabling the JavaFX keyboard on a mobile app, but honestly I wouldn't do it.

With KeyboardService you have control of when the software keyboard shows up and you can react accordingly, for instance moving up the view so the textField is fully visible. `keepVisibilityForNode` will do that, but this is convenient only if you have one textField/textArea in your view.

**Comment by mipastgt** [comment]
I'll give it a try tomorrow. Many thanks for the clarifications so far.

**Comment by mipastgt** [comment]
Just adding all my text input controls to the KeyboardService does exactly what I want. Nice.
Thank you very much.
Michael
