### ISSUE TITLE
Include directory from resources while compiling native Image via gluon client maven plugin

### ISSUE THREAD

**Issue by rnayabed** [gluonhq/client-maven-plugin#284]
I wrote a custom alert/combobox implementation for my project. Could not
use Gluon Mobile because its integrated tightly with our custom Theme
API. It works now!!

However, I have a small issue. My project root currently looks like this

root

     - src

     - resources

         - default/

             - config.xml

             - Themes/

             - Profiles/

             - Icons/

         - style.css

         - Roboto.ttf

When the config.xml file isnt found on local disk, the program just
copies all the contents of the `default` directory to the disk.

However, when i try to get `Main.class.getResource("default/").toURI()`
it returns a nullpointer. i added `-H:IncludeResources='*/*.*'` to
`<nativeImageArgs>` but it doesnt work. I also tried adding that under
`<resourcesList>` but that too did not work.

Any leads on how I can embed all the directories/files/ everything from
the resources folder onto the native image

StreamPi is going to be a real nice demonstration of how powerful
graalvm, gluon can be. I love your work!

**Comment by rnayabed** [comment]
This is a graalvm issue. `Class.getResource()` returns `resource:/<file location within the project>` which isn't usable in most cases. 

In order to get a file though, `Class.getResourceAsStream()` works perfectly! 

My workaround was to zip the entire directory, put it inside the resources directory and then extract it.

**Comment by jperedadnr** [comment]
Yes, `Main.class.getResource("default/")` doesn't return a "directory", from which you can list files.
You have to either use a `FileSystem` or `Class.getResourceAsStream()`.
