### ISSUE TITLE
Resource bundles in JSON files not working - what am I missing?

### ISSUE THREAD

**Issue by taranion** [gluonhq/client-maven-plugin#293]
I have problems definied resource bundles via JSON files.

According to the [documentation](https://docs.gluonhq.com/#_resource_bundles) you can either add your resource bundles in the pom.xml or to a file named **resourcebundles.json** in substrate/config.
The way via the pom.xml is working for me, but the list is growing large and I want to use the JSON file. I am aware that I need to write fully qualified names in a JSON file - but how is the json file structured?

Using a file like this
```
{
  "resources":[
  ],
  "bundles":[
    {"name":"my.fully.qualified.ResourceBundle"} 
  ]
}
```
does not help - neither naming it _resourcebundles.json_ nor _resourceconfig.json_.

**Comment by jperedadnr** [comment]
As you have linked, the documentation clearly says that you can provide a file `resourcebundles.json` or
`resourcebundles-$arch-$os.json` with fully qualified name of resource bundles that will be included like:

```
com.mycompany.myproject.mybundle1
com.mycompany.myproject.mybundle2
```

Note this format doesn't follow the [format]((https://github.com/oracle/graal/blob/master/substratevm/Resources.md#resource-bundles-in-native-image)) that GraalVM uses.

**Comment by taranion** [comment]
Ah, the file just has a .json suffix, but otherwise is just one bundle name per line - I did not expect that and ignored the example for not being a JSON file :flushed: . Thanks for the clarification
