### ISSUE TITLE
Resource bundles from configuration files ignored

### ISSUE THREAD

**Issue by taranion** [gluonhq/client-maven-plugin#306]
Adding resource bundles in the POMs `bundlelist` works well - every bundle listed there results in an `-H:IncludeResourceBundles` option when calling the native-image command.

Defining resources in extra configuration files in META-INF/substrate/config/ does not work.
I tried:

- **META-INF/substrate/config/resourcebundles.json** With the fully qualified bundle name as documented [here](https://docs.gluonhq.com/#_resource_bundles) and [here](https://github.com/gluonhq/client-maven-plugin/issues/293).
- Adding a bundles field to the **META-INF/substrate/config/resourceconfig.json**, like the native-image-agent produces and documented [here](https://www.graalvm.org/reference-manual/native-image/Resources/). While the "resources" field is evaluated and merged from all found config files, the resulting `target/client/x86_64-linux/gvm/resourceconfig-x86_64-linux.json` does not include the "bundles" field at all

None of this lead to either more `-H:IncludeResourceBundles`  entries or the resulting `target/client/x86_64-linux/gvm/resourceconfig-x86_64-linux.json` have the "bundles" field required for native-image.

**Comment by jperedadnr** [comment]
See the debug files under target.../gvm/log`, find `"Scanning for resource bundles"`, and see if any of the jars in your classpath (including your classes.jar) includes a `resourcebundles` file that is added. You should see that the JavaFX jars add a few.

About what is documented, and the other issue you have linked, I have to say... my bad... the docs are wrong... what is really used is [this](https://github.com/gluonhq/substrate/blob/master/src/main/java/com/gluonhq/substrate/Constants.java#L154): 

```
RESOURCE_BUNDLES_FILE = "resourcebundles"
```
which is more consistent with being a plain file and not being a json file.

So please try `META-INF/substrate/config/resourcebundles`? I'll fix the docs
