### ISSUE TITLE
Cannot install apk on android 10 (Failed to extract native libraries)

### ISSUE THREAD

**Issue by robert-picking** [gluonhq/client-maven-plugin#307]
As the title suggests, an apk generated with the client plugin cannot be installed on android 10 x86_64 device producing the error

```
$ adb -e install gluon-samples/HelloWorld/target/client/aarch64-android/gvm/HelloWorld.apk
Performing Streamed Install
adb: failed to install gluon-samples/HelloWorld/target/client/aarch64-android/gvm/HelloWorld.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

This can be duplicated by generating an apk for one of the gluon-samples, `HelloWorld` and attempting to install it on an android 10 device or emulator.  While the samples seem to be a little out of date, bumping the client plugin version to `0.1.38` still has this issue.

The generated apk can successfully be installed and run on a device or emulator running android 11.

**Comment by jperedadnr** [comment]
Sorry, x86_64 Android devices are not supported.

**Comment by lkSnatch** [comment]
Hello @jperedadnr , I've read several topic regarding non-supporting armeabi-v7a,armeabi by gluon mobile plugin. I've also read [this SO answers](https://stackoverflow.com/questions/36414219/install-failed-no-matching-abis-failed-to-extract-native-libraries-res-113) (not related to gluon) which say that it's possible to enforce gradle to use arm32 package, and arm32 file can run on both arm32 device and arm64 device, e.g. with specifying
```
ndk {
  abiFilters 'armeabi-v7a', 'x86', 'armeabi'
}
```
within '_android_' build section. And this section was present earlier in _javafxports_ with _jfxmobile_ section, like [here](https://github.com/jperedadnr/Game2048FX/blob/master/build.gradle). But now in the '_gluonfx_' section it causes the error, that there is no '_android()_' method.
Also I've seen some arch properties, like `robovm.ipaArchs=x86_64` [here](https://github.com/jperedadnr/Game2048FX/blob/master/gradle.properties).

So, I'm wondering is it possible somehow at all to use gluon mobile plugin (gradle or maven) and build apk for armeabi-v7a,armeabi? With some workarounds or specific properties? Or maybe it's possible to do without this plugin?
