### ISSUE TITLE
agentDir gets ignored

### ISSUE THREAD

**Issue by alaa-abu-zidan** [gluonhq/client-maven-plugin#312]
when I want to define different directory to store the config files , it is created with its sub-directories but never used, instead the default location is used.
"src/main/resources/META-INF/native-image/"

https://github.com/gluonhq/client-maven-plugin/blob/76f02d5805c45f357013d2a0cad3f418d8a8c4aa/src/main/java/com/gluonhq/NativeRunAgentMojo.java#L67

**Comment by jperedadnr** [comment]
`native-image` picks directly the config file under `src/main/resources/META-INF/native-image`, and `client:runagent` apply the default options to create such folder and files. Therefore, `agentDir` is read-only, so you can't modify it.

However, you can skip running `client:runagent`, and provide your own different set of options for `agentlib`.

**Comment by alaa-abu-zidan** [comment]
Sorry maybe I did not ask right, what is the "agentDir" is used for, isn't it for deciding where to store the scanned configuration files that the native-image agent detects?
If this is the purpose then it is not used, running client:runagent will not store configuration files in the desired location that is passed through "agentDir", they will be stored in src/main/resources/META-INF/native-image , regardless what you set agentDir to.

**Comment by jperedadnr** [comment]
As I mentioned:
> `agentDir` is read-only, so you can't modify it.

The user is not supposed to modify this value.

**Comment by alaa-abu-zidan** [comment]
Is it a design decision from your side to make it read only? coz as far as I know "-agentlib:native-image-agent=config-output-dir=/path/to/config-dir/ ..." can be set to whatever value, and this really necessary coz sometimes you need to separate per platform , for resources and jni at least. It does not make sense to mix all scanned configuration in one set, that will cause the executable to have multiple un necessary resources that will make it grow in size.

**Comment by jperedadnr** [comment]
You are right, you can configure the agentlib to put the files in different folders, based on your target platform, for instance.
However, then you would need to set that information for `native-image` as well, so it knows where to find those config files. 

So far, we just use a filter to remove platform specific classes from the config files, so these are valid for all target platforms.

For a more specialised use case, it is probably better to manually use the agentlib directly, without `client:runagent`.

**Comment by alaa-abu-zidan** [comment]
I think you are right on this. I will close the issue. Thank you.
