### ISSUE TITLE
Support for ios-sim target is broken

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/client-maven-plugin#88]
If I try to build one of the examples for the ios-sim target, I only get the following error message:
```
We will now compile your code for x86_64-apple-ios. This may take some time.
Not a dir
java.lang.RuntimeException: Error downloading zips: Error downloading from http://download2.gluonhq.com/substrate/staticjdk/labs-staticjdk-ios-x86_64-gvm-14-ea+5.zipinto /Users/mpaus/.gluon/substrate/labs-staticjdk-ios-x86_64-gvm-14-ea+5.zip: http://download2.gluonhq.com/substrate/staticjdk/labs-staticjdk-ios-x86_64-gvm-14-ea+5.zip, []
```
I am using the client-maven-plugin 0.1.10 and GraalVM 19.3.0.2.

**Comment by johanvos** [comment]
We don't support ios-simulator yet.

**Comment by mipastgt** [comment]
Then you should at least modify the documentation https://docs.gluonhq.com/client/ The ios-sim target is explicitly advertise there.

**Comment by johanvos** [comment]
You're right. Sorry about that.
Removed.
