### ISSUE TITLE
Building for Android does not work on Mac

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/client-maven-plugin#89]
As there are examples shown on Twitter of successful Android builds, I also wanted to give it a try but all I got was:
```
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.10:compile (default-cli) on project hellofx: Error: You specified an android ndk, but it doesn't contain /Users/mpaus/Library/Android/sdk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/ldlld -> [Help 1]
```
Obviously some path are hard-coded for a Linux environment.

I am using the client-maven-plugin 0.1.10 and GraalVM 19.3.0.2.

**Comment by johanvos** [comment]
We don't support Android development yet on Mac. (instructions for Linux will follow).
