### ISSUE TITLE
Specifying attach client version will still try to load default version

### ISSUE THREAD

**Issue by johanvos** [gluonhq/client-maven-plugin#92]
reproduce 

in maven-client-plugin, NativeBaseMojo: set attachVersion defaultValue to "4.0.5"

in HelloGluon:
set client.attachVersion to 4.0.4-SNAPSHOT

mvn client:compile

Errors will be shown since "4.0.5" can't be found. 

In NativeBaseMojo.getAttachDependencies, attachVersion is always the default one, not the one defined in the pom.xml

**Comment by jperedadnr** [comment]
Should be fixed with #97
